import{a as E,S as v,i as s}from"./assets/vendor-5YrzWRhu.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const d of n.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&u(d)}).observe(document,{childList:!0,subtree:!0});function r(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function u(t){if(t.ep)return;t.ep=!0;const n=r(t);fetch(t.href,n)}})();const B="https://pixabay.com/api/",I="51715057-18e32c1eb7da364006690b614",R=15;async function f(o,e=1){return(await E.get(B,{params:{key:I,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:R,page:e}})).data}const h=document.getElementById("gallery"),p=document.getElementById("load-more"),m=document.querySelector(".loader");let P=new v(".gallery a",{captionsData:"alt",captionDelay:250});function g(o){const e=o.map(r=>`
      <li class="photo-card">
        <a href="${r.largeImageURL}">
          <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${r.likes}</p>
          <p><b>Views</b> ${r.views}</p>
          <p><b>Comments</b> ${r.comments}</p>
          <p><b>Downloads</b> ${r.downloads}</p>
        </div>
      </li>`).join("");h.insertAdjacentHTML("beforeend",e),P.refresh()}function $(){h.innerHTML=""}function y(){m.classList.remove("hidden")}function b(){m.classList.add("hidden")}function L(){p.classList.remove("hidden")}function w(){p.classList.add("hidden")}const M=document.getElementById("search-form"),S=document.getElementById("gallery"),A=document.getElementById("load-more");let a="",i=1;const l=15;let c=0;M.addEventListener("submit",async o=>{if(o.preventDefault(),a=o.target.elements["search-text"].value.trim(),!!a){i=1,$(),w(),y();try{const e=await f(a,i,l);if(!e||!e.hits.length){s.info({title:"Info",message:`No results found for "${a}".`,position:"topRight"});return}g(e.hits),c=Math.ceil(e.totalHits/l),i<c?L():s.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{s.error({title:"Error",message:"Something went wrong. Try again later.",position:"topRight"})}finally{b()}}});A.addEventListener("click",async()=>{i+=1,w(),y();try{const o=await f(a,i,l);if(!o||!o.hits.length){s.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}const e=S.lastElementChild;if(g(o.hits),c=Math.ceil(o.totalHits/l),i<c?L():s.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),e){const r=e.getBoundingClientRect().height||200;window.scrollBy({top:r*2,behavior:"smooth"})}}catch{s.error({title:"Error",message:"Something went wrong. Try again later.",position:"topRight"})}finally{b()}});
//# sourceMappingURL=index.js.map
