import{a as v,S as I,i}from"./assets/vendor-5YrzWRhu.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const B="https://pixabay.com/api/",P="51715057-18e32c1eb7da364006690b614",f=44;async function m(o,r=1){return(await v.get(B,{params:{key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:f,page:r}})).data}const p=document.getElementById("gallery"),h=document.getElementById("load-more"),y=document.querySelector(".loader");let A=new I(".gallery a",{captionsData:"alt",captionDelay:250});function g(o){const r=o.map(e=>`
      <li class="photo-card">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${e.likes}</p>
          <p><b>Views</b> ${e.views}</p>
          <p><b>Comments</b> ${e.comments}</p>
          <p><b>Downloads</b> ${e.downloads}</p>
        </div>
      </li>`).join("");p.insertAdjacentHTML("beforeend",r),A.refresh()}function R(){p.innerHTML=""}function b(){y.classList.remove("hidden")}function L(){y.classList.add("hidden")}function E(){h.classList.remove("hidden")}function w(){h.classList.add("hidden")}const $=document.getElementById("search-form"),x=document.getElementById("load-more"),u=document.getElementById("gallery");let c="",n=1,d=0;$.addEventListener("submit",async o=>{o.preventDefault();const r=o.target.elements["search-text"].value.trim();if(!r){i.error({title:"Error",message:"Please enter a search term",position:"topRight",timeout:3e3});return}c=r,n=1,R(),w(),b();try{const e=await m(c,n);if(!e||!Array.isArray(e.hits))throw new Error("Unexpected API response");if(e.totalHits===0){i.info({title:"Info",message:"No images found for this query",position:"topRight",timeout:3e3});return}g(e.hits),d=Math.ceil(e.totalHits/f),n<d&&E()}catch(e){i.error({title:"Error",message:e.message,position:"topRight",timeout:3e3})}finally{L()}});x.addEventListener("click",async()=>{n++,w(),b();try{const o=await m(c,n);if(!o||!Array.isArray(o.hits))throw new Error("Unexpected API response");if(o.hits.length===0){i.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3});return}const r=u.lastElementChild;g(o.hits);const e=r?r.nextElementSibling:u.firstElementChild;if(e){const{height:a}=e.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}n<d?E():i.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3})}catch(o){i.error({title:"Error",message:o.message,position:"topRight",timeout:3e3})}finally{L()}});
//# sourceMappingURL=index.js.map
