import{a as E,S as v,i as s}from"./assets/vendor-5YrzWRhu.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&d(c)}).observe(document,{childList:!0,subtree:!0});function r(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function d(t){if(t.ep)return;t.ep=!0;const n=r(t);fetch(t.href,n)}})();const B="https://pixabay.com/api/",I="51715057-18e32c1eb7da364006690b614",R=15;async function u(o,e=1){return(await E.get(B,{params:{key:I,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:R,page:e}})).data}const f=document.getElementById("gallery"),m=document.getElementById("load-more");document.querySelector(".loader");let P=new v(".gallery a",{captionsData:"alt",captionDelay:250});function h(o){const e=o.map(r=>`
      <li class="photo-card">
        <a href="${r.largeImageURL}">
          <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${r.likes}</p>
          <p><b>Views</b> ${r.views}</p>
          <p><b>Comments</b> ${r.comments}</p>
          <p><b>Downloads</b> ${r.downloads}</p>
        </div>
      </li>`).join("");f.insertAdjacentHTML("beforeend",e),P.refresh()}function $(){f.innerHTML=""}function p(){m.classList.remove("hidden")}function g(){m.classList.add("hidden")}const M=document.getElementById("search-form"),S=document.getElementById("gallery"),A=document.getElementById("load-more"),y=document.querySelector(".loader");let a="",i=1;const b=15;let l=0;function L(){y.classList.remove("hidden")}function w(){y.classList.add("hidden")}M.addEventListener("submit",async o=>{if(o.preventDefault(),a=o.target.elements["search-text"].value.trim(),!a){s.warning({title:"Warning",message:"Please enter a search term.",position:"topRight",timeout:2e3});return}i=1,$(),g(),L();try{const e=await u(a,i);if(!e||!e.hits.length){s.info({title:"Info",message:`No results found for "${a}".`,position:"topRight",timeout:3e3});return}h(e.hits),l=Math.ceil(e.totalHits/b),i<l?p():s.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3})}catch{s.error({title:"Error",message:"Something went wrong. Try again later.",position:"topRight",timeout:3e3})}finally{w()}});A.addEventListener("click",async()=>{i+=1,g(),L();try{const o=await u(a,i);if(!o||!o.hits.length){s.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3});return}const e=S.lastElementChild;if(h(o.hits),l=Math.ceil(o.totalHits/b),i<l?p():s.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3}),e){const r=e.getBoundingClientRect().height||200;window.scrollBy({top:r*2,behavior:"smooth"})}}catch{s.error({title:"Error",message:"Something went wrong. Try again later.",position:"topRight",timeout:3e3})}finally{w()}});
//# sourceMappingURL=index.js.map
